// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using µMedlogr.core;

#nullable disable

namespace µMedlogr.core.Migrations
{
    [DbContext(typeof(µMedlogrContext))]
    [Migration("20231129134738_Nullable")]
    partial class Nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUserPerson", b =>
                {
                    b.Property<string>("CareGiversId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PeopleInCareOfId")
                        .HasColumnType("int");

                    b.HasKey("CareGiversId", "PeopleInCareOfId");

                    b.HasIndex("PeopleInCareOfId");

                    b.ToTable("AppUserPerson");
                });

            modelBuilder.Entity("HealthRecordSymptomType", b =>
                {
                    b.Property<int>("CurrentSymptomsId")
                        .HasColumnType("int");

                    b.Property<int>("RecordsId")
                        .HasColumnType("int");

                    b.HasKey("CurrentSymptomsId", "RecordsId");

                    b.HasIndex("RecordsId");

                    b.ToTable("HealthRecordSymptomType");
                });

            modelBuilder.Entity("µMedlogr.core.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MeId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecordEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("HealthRecordsEntrys");
                });

            modelBuilder.Entity("µMedlogr.core.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("WeightInKg")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HealthRecordEntryId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectiveSeverity")
                        .HasColumnType("int");

                    b.Property<int>("SymptomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeSymptomWasChecked")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordEntryId");

                    b.HasIndex("SymptomId");

                    b.ToTable("SymptomMeasurements");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SymptomTypes");
                });

            modelBuilder.Entity("µMedlogr.core.Models.TemperatureData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<float>("Measurement")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeOfMeasurement")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("TemperatureDatas");
                });

            modelBuilder.Entity("AppUserPerson", b =>
                {
                    b.HasOne("µMedlogr.core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CareGiversId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("µMedlogr.core.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleInCareOfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthRecordSymptomType", b =>
                {
                    b.HasOne("µMedlogr.core.Models.SymptomType", null)
                        .WithMany()
                        .HasForeignKey("CurrentSymptomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("µMedlogr.core.Models.HealthRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("µMedlogr.core.Models.AppUser", b =>
                {
                    b.HasOne("µMedlogr.core.Models.Person", "Me")
                        .WithMany()
                        .HasForeignKey("MeId");

                    b.Navigation("Me");
                });

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecordEntry", b =>
                {
                    b.HasOne("µMedlogr.core.Models.HealthRecord", null)
                        .WithMany("Entries")
                        .HasForeignKey("HealthRecordId");
                });

            modelBuilder.Entity("µMedlogr.core.Models.Person", b =>
                {
                    b.HasOne("µMedlogr.core.Models.HealthRecord", "HealthRecord")
                        .WithOne("Record")
                        .HasForeignKey("µMedlogr.core.Models.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomMeasurement", b =>
                {
                    b.HasOne("µMedlogr.core.Models.HealthRecordEntry", null)
                        .WithMany("Measurements")
                        .HasForeignKey("HealthRecordEntryId");

                    b.HasOne("µMedlogr.core.Models.SymptomType", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("µMedlogr.core.Models.TemperatureData", b =>
                {
                    b.HasOne("µMedlogr.core.Models.HealthRecord", null)
                        .WithMany("Temperatures")
                        .HasForeignKey("HealthRecordId");
                });

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecord", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Record");

                    b.Navigation("Temperatures");
                });

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecordEntry", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
