// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using µMedlogr.core;

#nullable disable

namespace µMedlogr.core.Migrations
{
    [DbContext(typeof(µMedlogrContext))]
    [Migration("20231124121403_SymptomChanges")]
    partial class SymptomChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("µMedlogr.core.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("WeightInKg")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectiveSeverity")
                        .HasColumnType("int");

                    b.Property<int>("SymptomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeSymptomWasChecked")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("SymptomId");

                    b.ToTable("SymptomMeasurements");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("SymptomTypes");
                });

            modelBuilder.Entity("µMedlogr.core.Models.TemperatureData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Measurement")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeOfMeasurement")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TemperatureDatas");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomMeasurement", b =>
                {
                    b.HasOne("µMedlogr.core.Models.HealthRecord", null)
                        .WithMany("SymtomLog")
                        .HasForeignKey("HealthRecordId");

                    b.HasOne("µMedlogr.core.Models.SymptomType", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("µMedlogr.core.Models.SymptomType", b =>
                {
                    b.HasOne("µMedlogr.core.Models.HealthRecord", null)
                        .WithMany("CurrentSymptoms")
                        .HasForeignKey("HealthRecordId");
                });

            modelBuilder.Entity("µMedlogr.core.Models.HealthRecord", b =>
                {
                    b.Navigation("CurrentSymptoms");

                    b.Navigation("SymtomLog");
                });
#pragma warning restore 612, 618
        }
    }
}
