name: Show Commit Count

on:
  push:
    branches:
      - main

jobs:
  show-commit-count:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Show Commit Count
      run: |
        echo "Number of Commits: $(git rev-list --count --all)"
      shell: bash
