name: ETCC Integration Tests

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow-dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:         
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
          
    - name: Build
      run: dotnet build --no-restore --configuration release

    - name: Test
      run: dotnet test --logger "console;verbosity=detailed"
      
