name: ETCC Integration Tests

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__DefaultConnection: "Server=localhost,1433;Initial Catalog=µMedlogr; User Id=sa; Password=NotARealPassw0rd!;Trusted_Connection=False;TrustServerCertificate=True"
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env: 
          MSSQL_SA_PASSWORD: NotARealPassw0rd!
          ACCEPT_EULA: Y
        ports: 
          - "1433:1433"
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:         
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
          
    - name: Build
      run: dotnet build --no-restore --configuration release

    - name: Test
      run: dotnet test --filter Category=Integration --logger "console;verbosity=detailed"
      
